chore(prompts): updated apache
newrelic/open-install-library pull request #144
Opened 2021-01-22 22:33 UTC by jbeveland27

Updated all OHI prompts to be more succinct.

Also updated Cassandra to use correct port based on #53

2021-01-22 22:51 UTC, Julien4218 commented on recipes/newrelic/cassandra/debian.yml
> -    default: 7199
7199 should be the correct value. This is also what we document https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/cassandra-monitoring-integration

2021-01-22 22:51 UTC, Julien4218 commented on recipes/newrelic/cassandra/rhel.yml
> -    default: 7199
7199 should be the correct value. This is also what we document https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/cassandra-monitoring-integration

2021-01-22 22:52 UTC, Julien4218 commented on test/deploy/linux/cassandra/install/debian/roles/configure/tasks/main.yml
> -    shell: "echo export NR_CLI_DB_PORT=7199 >> ~/.bashrc"
7199 should be the correct value. This is also what we document https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/cassandra-monitoring-integration

2021-01-22 22:52 UTC, Julien4218 commented on test/deploy/linux/cassandra/install/linux2/roles/configure/tasks/main.yml
> -    shell: "echo export NR_CLI_DB_PORT=7199 >> ~/.bashrc"
7199 should be the correct value. This is also what we document https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/cassandra-monitoring-integration

2021-01-22 22:53 UTC, Julien4218 requested changes
I dont believe the cassandra port change is correct.
We should validate all the text changes with an XD person, or rishi, or both.

2021-01-23 03:14 UTC, jbeveland27 commented
Agreed, changed back to 7199 for Cassandra. Not sure why the issue was written with the other port.

Also agreed on validating the changes with XD. Maybe it's appropriate to merge these changes, and have Emma/Rishi/etc. review from here forward? At the very least this establishes consistency for every recipe.

2021-01-25 16:21 UTC, Julien4218 approved these changes

2021-01-25 16:22 UTC, Julien4218 commented
@jbeveland27  ✔️

2021-01-25 16:37 UTC, merged