feat: infrastructure agent status check after installation, just Linux
newrelic/open-install-library pull request #387
Opened 2021-05-31 13:21 UTC by varas

2021-06-01 08:02 UTC, jlegoff commented
Looks good to me, although it introduces an additional risk if the 8003 port is already taken. What do you think @Julien4218 ?

2021-06-01 15:15 UTC, Julien4218 requested changes
I don't think we can assume port 8003 is free for us to use.
I assume we would have to document this, and handle the case when the port is not available on the host. Should we have logic to try another port, what do we do in the end when we can't find a port (fail the install, or the health check and skip over?)

2021-06-01 17:29 UTC, Julien4218 requested changes
@varas we've talked about this work with @jlegoff 
In the short term, let's use a less likely to be used port number, a 5 digit one for instance
I've added a new MMF to take advantage of this work, so that we can fetch the entityGuid using the local endpoint in https://newrelic.atlassian.net/browse/VIRTUOSO-997

2021-06-14 17:52 UTC, Julien4218 approved these changes

2021-06-14 17:52 UTC, merged