feat: infrastructure-agent installation recipe for macos
newrelic/open-install-library pull request #478
Opened 2021-08-04 06:48 UTC by rubenruizdegauna

Recipe to install the infrastructure agent in macos host. 
On-hold until brew package is finished.

2021-08-16 18:48 UTC, Julien4218 commented
@brushknight could you let us know when the infra macos agent is released. We'll do some testing for this recipe and review/merge/deploy afterward.
Thank You

2021-08-16 22:58 UTC, ctrombley requested changes

2021-08-16 22:58 UTC, ctrombley commented on recipes/newrelic/infrastructure/darwin.yml
> +          HOMEBREW_NO_AUTO_UPDATE=1 brew install newrelic-infra -q
This needs to be updated to the following, so brew can run in non-root mode:

```
sudo -i -u $SUDO_USER brew install newrelic-infra -q
```

2021-08-16 22:58 UTC, ctrombley commented on recipes/newrelic/infrastructure/darwin.yml
> +          brew services restart newrelic-infra-agent
This needs to be updated to the following, so brew can run in non-root mode:

```
sudo -i -u $SUDO_USER brew services restart newrelic-infra-agent
```

2021-08-18 15:44 UTC, Julien4218 submitted a review, later dismissed

2021-08-18 16:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/open-install-library?pullRequest=478) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/open-install-library?pullRequest=478) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: brushknight<br/>:white_check_mark: rubenruizdegauna<br/>:x: mro<br/><hr/>**mro** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/open-install-library?pullRequest=478) it.</sub>

2021-08-18 16:20 UTC, ctrombley approved these changes

2021-08-18 16:31 UTC, merged